name: CI

on:
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install root dependencies
        run: yarn --frozen-lockfile

      - name: Install app dependencies
        run: cd src/nvim-awesome.app && yarn --frozen-lockfile
        
      - name: Run lint
        run: yarn frontend:lint

      - name: Run prettier
        run: yarn frontend:prettier

      - name: Run build
        run: yarn frontend:build

